name: preview
on:
  pull_request:
    branches:
      - "main"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install --immutable
      - run: pnpm vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - id: deploy
        run: echo "::set-output name=url::$(pnpm vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
